services:
  postgres:
    image: postgres:16-alpine
    container_name: curriculos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: curriculos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - curriculos_pgdata:/var/lib/postgresql/data

volumes:
  curriculos_pgdata:
